### ISSUE TITLE
Logic error in Firewall rule any/any created ?

### ISSUE THREAD

**Issue by wagga40** [mdecrevoisier/SIGMA-detection-rules#9]
In the following rule : [Firewall rule any/any created](https://github.com/mdecrevoisier/SIGMA-detection-rules/blob/main/windows-firewall/win-os-firewall%20rule%20any-any%20created%20(firewall).yaml)

The related EVTX is [here](https://github.com/mdecrevoisier/EVTX-to-MITRE-Attack/tree/master/TA0005-Defense%20Evasion/T1562.004-Impair%20Defenses-Disable%20or%20Modify%20System%20Firewall)

I think the important fields are : 

```json
"LocalAddresses": "*",
"LocalPorts": "",
"RemoteAddresses": "*",
"RemotePorts": "",
```

But the rule only checks for `LocalPorts ` and `RemotePorts` : 

```yaml
detection:
  selection:
    EventID:
      - 2004  # new rule created
      - 2005  # existing rule modified
    Action: 3 # allow
    LocalPorts: *
    RemotePorts: *
```

Shouldn't you add a check for  `LocalAddresses` and `RemoteAddresses` equal to `'\*'` ?
